const TABS = [
  ["redemptions", "Redemptions", "/dashboard/rewards/redemptions"],
  ["shop", "Shop Items", "/dashboard/rewards/shop"],
  ["channel", "Channel", "/dashboard/rewards/channel"],
  ["maps", "Mappings", "/dashboard/rewards/maps"],
  ["viewers", "Viewers", "/dashboard/rewards/viewers"],
  ["history", "Ledger", "/dashboard/rewards/history"],
];

function tabs(active) {
  return `<nav class="v3-tabs" aria-label="Rewards & Shop sections">${TABS.map(([key, label, href]) => `<a class="v3-tab${active === key || (active === "rewards" && key === "maps") ? " is-on" : ""}"${active === key || (active === "rewards" && key === "maps") ? ' aria-current="page"' : ""} href="${href}">${label}</a>`).join("")}</nav>`;
}

function page(tab, sub, body) {
  return `<div class="v3-head"><h1>Rewards &amp; Shop</h1><p class="v3-head-sub">${sub}</p></div>${tabs(tab)}${body}`;
}

const channel = `<section class="v3-table-card cr-channel-card" id="cr-channel"><div id="cr-channel-connected" hidden><div class="cr-channel-summary"><div class="cr-kick-mark">K</div><div><h2>@<span id="cr-channel-name"></span> on Kick</h2><span class="v3-chip v3-chip--fulfilled">● Connected</span></div><button id="cr-channel-disconnect" class="btn btn--sm btn--danger" type="button">Disconnect</button></div><div class="cr-channel-facts"><div><span>CHANNEL STATUS</span><b id="cr-channel-live">Connected</b></div><div><span>TOKEN HEALTH</span><b id="cr-channel-token">No Kick token · connect Kick</b></div></div><span id="cr-channel-id" hidden></span><span id="cr-channel-linked" hidden></span><a id="cr-channel-reconnect" href="/auth/kick" hidden>Reconnect Kick</a></div><div id="cr-channel-connect-wrap"><div class="cr-channel-summary"><div class="cr-kick-mark">K</div><div><h2>Connect your Kick channel</h2><p class="v3-head-sub">Link Kick to turn channel-point rewards into credits.</p></div></div><a id="cr-channel-connect" class="btn btn--accent" href="/auth/kick">Connect with Kick</a><details class="cr-advanced"><summary>Manual channel ID</summary><form class="grid2" id="cr-channel-form"><div class="field"><label for="cr-channel-id-input">Kick channel/broadcaster ID</label><input id="cr-channel-id-input" name="externalId" type="text" placeholder="12345678" /></div><div class="field"><label for="cr-channel-name-input">Channel name (optional)</label><input id="cr-channel-name-input" name="name" type="text" placeholder="yourchannel" /></div><div class="field field--full"><button class="btn" type="submit" id="cr-channel-submit">Save channel</button><p class="status" id="cr-channel-status" role="status" aria-live="polite"></p></div></form></details></div></section>`;

const mappings = `<section class="v3-table-card" id="cr-rewards"><div class="v3-section-head"><div><h2>Reward → Credit Mappings</h2><p class="v3-head-sub v3-head-sub--mono" id="cr-reward-usage"></p></div><a class="btn btn--sm btn--accent" id="cr-add-mapping" data-reveal-mapping href="/dashboard/rewards/maps#cr-reward-form">+ Add mapping</a></div><div class="cr-table-scroll"><table class="v3-table"><thead><tr><th>KICK REWARD EVENT</th><th>TYPE / CONDITION</th><th>CREDITS AWARDED</th><th>STATUS</th><th class="ta-r">ACTIONS</th></tr></thead><tbody id="cr-reward-list"></tbody></table></div><div class="cr-form-panel"><details class="cr-advanced"><summary>Manual reward mapping</summary><form class="grid2" id="cr-reward-form"><input type="hidden" id="cr-reward-id" /><div class="field"><label for="cr-reward-kick-id">Kick reward ID</label><input id="cr-reward-kick-id" name="kickRewardId" type="text" required /></div><div class="field"><label for="cr-reward-title">Reward title</label><input id="cr-reward-title" name="kickRewardTitle" type="text" required /></div><div class="field"><label for="cr-reward-cost">Kick point cost</label><input id="cr-reward-cost" name="kickRewardCost" type="number" min="0" value="100" required /></div><div class="field"><label for="cr-reward-credits">Credits granted</label><input id="cr-reward-credits" name="credits" type="number" min="1" value="50" required /></div><div class="field field--full"><button class="btn" type="submit" id="cr-reward-submit">Save mapping</button><p class="status" id="cr-reward-status" role="status" aria-live="polite"></p></div></form></details><details class="cr-advanced"><summary>Create a reward on Kick</summary><form class="grid2" id="cr-reward-create-form"><div class="field"><label for="cr-reward-create-title">Title</label><input id="cr-reward-create-title" name="title" type="text" required maxlength="50" /></div><div class="field"><label for="cr-reward-create-cost">Kick point cost</label><input id="cr-reward-create-cost" name="cost" type="number" min="1" value="100" required /></div><div class="field"><label for="cr-reward-create-credits">Credits granted</label><input id="cr-reward-create-credits" name="credits" type="number" min="1" value="50" required /></div><div class="field"><label for="cr-reward-create-color">Background color</label><input id="cr-reward-create-color" name="backgroundColor" type="color" value="#00e701" /></div><div class="field field--full"><label for="cr-reward-create-desc">Description</label><input id="cr-reward-create-desc" name="description" type="text" maxlength="200" /></div><div class="field field--full"><button class="btn btn--accent" type="submit" id="cr-reward-create-submit">Create in Kick</button><p class="status" id="cr-reward-create-status" role="status" aria-live="polite"></p></div></form></details></div></section>`;
const mappingMarkup = mappings
  .replace('</div><div class="cr-table-scroll">', '</div><div class="cr-list-toolbar" id="cr-mapping-toolbar"></div><div class="cr-table-scroll">')
  .replace('</table></div><div class="cr-form-panel">', '</table></div><div class="v3-table-foot" id="cr-mapping-foot"></div><div class="cr-form-panel">');

const shop = `<section class="cr-shop-layout" id="cr-shop"><div class="v3-section-head"><p class="v3-head-sub v3-head-sub--mono" id="cr-shop-usage"></p><button class="btn btn--sm btn--accent" type="button" id="cr-shop-new">+ Create item</button></div><div class="cr-shop-grid"><div class="cr-shop-list"><div class="v3-empty" id="cr-shop-empty" hidden><div class="v3-empty-ic">□</div><h2>No shop items yet</h2><p>Create an item viewers can redeem with credits.</p><div class="v3-empty-actions"><button class="btn btn--sm btn--accent" type="button" data-cr-shop-create>+ Create item</button></div></div><div class="cr-shop-cards" id="cr-shop-list"></div></div><aside class="cr-shop-drawer" id="cr-shop-drawer" hidden><div class="cr-drawer-head"><h2 id="cr-shop-drawer-title">Create New Shop Item</h2><button type="button" class="cr-drawer-close" id="cr-shop-close" aria-label="Close">×</button></div><form id="cr-shop-form"><input type="hidden" id="cr-shop-item-id" /><div class="field"><label for="cr-shop-name">Item Name</label><input id="cr-shop-name" name="name" type="text" required /></div><div class="field"><label for="cr-shop-desc">Description</label><textarea id="cr-shop-desc" name="description" rows="3"></textarea></div><div class="grid2"><div class="field cr-suffix-field"><label for="cr-shop-cost">Cost</label><input id="cr-shop-cost" name="cost" type="number" min="1" value="100" required /></div><div class="field cr-suffix-field"><label for="cr-shop-stock">Stock</label><input id="cr-shop-stock" name="stock" type="number" min="0" placeholder="∞" /><span>LIMIT</span></div></div><label class="cr-toggle-row"><span><b>Active</b><small>Visible and redeemable by viewers.</small></span><input type="checkbox" class="v3-toggle" id="cr-shop-active" name="active" checked /></label><div class="cr-drawer-actions"><button class="btn" type="button" id="cr-shop-cancel">Cancel</button><button class="btn btn--accent" type="submit" id="cr-shop-submit">Save Item</button></div><p class="status" id="cr-shop-status" role="status" aria-live="polite"></p></form></aside></div></section>`;

const redemptions = `<section class="cr-redemptions-wrap" id="cr-redemptions-wrap"><div class="v3-table-card cr-redemption-summary"><div id="cr-redemption-channel" class="v3-chip v3-chip--refunded">● Connected to @<span></span></div><div class="cr-counters"><div><span>PENDING QUEUE</span><b id="cr-pending-counter">0 / 0</b><small>limit</small></div><i></i><div><span>FULFILLED (THIS MONTH)</span><b id="cr-fulfilled-counter">0 / 0</b><small>limit</small></div></div></div><div class="v3-table-card cr-list-card" id="cr-redemptions"><div class="cr-list-toolbar" id="cr-redemption-toolbar"><p class="status" id="cr-redemption-status" role="status" aria-live="polite"></p></div><div class="cr-table-scroll"><table class="v3-table"><thead><tr><th>VIEWER</th><th>ITEM</th><th class="num">COST</th><th>STATUS</th><th>REQUESTED</th><th class="ta-r">ACTIONS</th></tr></thead><tbody id="cr-redemption-list"></tbody></table></div><div class="v3-empty" id="cr-redemption-empty" hidden><div class="v3-empty-ic">□</div><h2>No redemptions yet</h2><p>Viewer requests will appear here.</p></div><div class="v3-table-foot" id="cr-redemption-foot"></div></div></section>`;

const viewers = `<section class="v3-table-card" id="cr-viewers"><div class="v3-section-head"><div><h2>Viewer balances</h2><p class="v3-head-sub">Credits earned and spent by viewers on this board.</p></div><p class="status" id="cr-viewer-status" role="status" aria-live="polite"></p></div><div class="cr-table-scroll"><table class="v3-table"><thead><tr><th>KICK USER</th><th class="num">BALANCE</th><th class="num">TOTAL EARNED</th><th class="num">TOTAL SPENT</th><th>LAST EARNED</th><th class="ta-r">ACTIONS</th></tr></thead><tbody id="cr-viewer-list"></tbody></table></div><div class="v3-empty" id="cr-viewer-empty" hidden><h2>No viewers yet.</h2></div></section>`;
const history = `<section class="v3-table-card" id="cr-history"><div class="v3-section-head"><div><h2>Viewer ledger history</h2><p class="v3-head-sub">Search a Kick viewer across your boards.</p></div></div><form class="cr-history-form" id="cr-history-form"><input id="cr-history-username" placeholder="Kick username" /><button class="btn btn--accent" id="cr-history-search" type="submit">Search</button><span class="status" id="cr-history-status"></span></form><div class="cr-table-scroll"><table class="v3-table"><thead><tr><th>BOARD</th><th class="num">BALANCE</th><th class="num">EARNED</th><th class="num">SPENT</th><th class="num">PENDING</th><th class="num">REDEMPTIONS</th><th></th></tr></thead><tbody id="cr-history-list"></tbody></table></div><div class="v3-empty" id="cr-history-empty"><h2>Search for a viewer</h2></div></section>`;
const channelSecondary = `<section class="v3-table-card cr-channel-secondary"><div class="cr-usage-panel"><h2>Plan usage</h2><div id="cr-usage" class="cr-usage-grid"></div></div><div class="cr-auth-panel"><h2>Viewer login settings</h2><form id="cr-viewer-auth-form"><div class="cr-auth-options"><label class="cr-auth-option"><input type="checkbox" id="cr-viewer-auth-kick" name="kick" checked /><span>Allow “Log in with Kick”</span></label><label class="cr-auth-option"><input type="checkbox" id="cr-viewer-auth-discord" name="discord" checked /><span>Allow “Log in with Discord”</span></label><label class="cr-auth-option"><input type="checkbox" id="cr-viewer-auth-public" name="public" checked /><span>Allow public username lookup &amp; redeem</span></label></div><div><button class="btn" type="submit" id="cr-viewer-auth-submit">Save settings</button><p class="status" id="cr-viewer-auth-status" role="status" aria-live="polite"></p></div></form></div></section>`;
export const channelPage = page("channel", "Configure platform integrations and reward triggers.", `${channel}${mappingMarkup}${channelSecondary}`);
export const rewardsPage = page("rewards", "Configure platform integrations and reward triggers.", mappingMarkup);
export const mapsPage = page("maps", "Configure platform integrations and reward triggers.", mappingMarkup);
export const shopPage = page("shop", "Manage viewer items and custom channel redemptions.", shop);
export const viewersPage = page("viewers", "Review viewer balances and credit activity.", viewers);
export const redemptionsPage = page("redemptions", "Approve viewer redemptions and keep fulfillment moving.", redemptions);
export const historyPage = page("history", "Review viewer credit history across your boards.", history);
