-- NO-OP: This migration originally targeted sites(postback_key) which doesn't exist.
-- The index on users(postback_key) already exists from migration 20260704000009 (idx_users_postback_key).
-- Kept as no-op to preserve migration sequence.
